apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild: 
    projectId: ticketing-dev-355503
  artifacts:
    # - image: jsmr04/auth
    - image: us.gcr.io/ticketing-dev-355503/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts' 
            dest: .